"use client";

import {useEffect,useState} from "react";
import {CheckCircle2,XCircle,HelpCircle,ExternalLink} from "lucide-react";

type Request={id:string;name:string;type:string;website:string|null;country:string;contactEmail:string;applicantName:string;jobTitle:string;department:string|null;employmentType:string|null;associationDuration:string|null;phone:string|null;authorizationReason:string;officialProfileUrl:string|null;evidenceUrl:string|null;evidenceDescription:string|null;status:string;reviewNote:string|null;createdAt:string};

export default function AdminOrganizationVerificationPage(){
 const [items,setItems]=useState<Request[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/organization-verification",{cache:"no-store"}),d=await r.json();if(!r.ok){setError(d.error||"Could not load requests.");return}setItems(d.requests)}catch{setError("Could not load requests.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function review(id:string,action:"APPROVE"|"REJECT"|"MORE_INFORMATION_REQUIRED"){setBusy(id+action);setError("");try{const r=await fetch("/api/admin/organization-verification",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:id,action,reviewNote:notes[id]||""})}),d=await r.json();if(!r.ok){setError(d.error||"Could not update request.");return}await load()}catch{setError("Could not update request.")}finally{setBusy("")}}
 return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
  <div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">XROVIA Administration</p><h1 className="mt-1 text-3xl font-black text-slate-950">Organization verification requests</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Review organizations that do not have an official organization email. Approval sends a one-time registration code to the applicant's existing email address.</p></div>
  {error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {loading?<div className="mt-8 rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading requests...</div>:items.length===0?<div className="mt-8 rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">No organization verification requests.</div>:
  <div className="mt-8 space-y-6">{items.map(x=><article key={x.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
   <div className="border-b border-slate-200 p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{x.type.replaceAll("_"," ")}</span><h2 className="mt-3 text-2xl font-black text-slate-950">{x.name}</h2><p className="mt-1 text-xs text-slate-500">{x.country} · {x.contactEmail}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{x.status.replaceAll("_"," ")}</span></div></div>
   <div className="grid gap-6 p-6 lg:grid-cols-2">
    <Info title="Applicant" rows={[["Name",x.applicantName],["Email",x.contactEmail],["Position",x.jobTitle],["Department",x.department||"Not provided"],["Relationship",x.employmentType||"Not provided"],["Association",x.associationDuration||"Not provided"],["Phone",x.phone||"Not provided"]]}/>
    <Info title="Organization" rows={[["Website",x.website||"Not provided"],["Country",x.country],["Submitted",new Date(x.createdAt).toLocaleString()] ]}/>
   </div>
   <div className="grid gap-6 border-t border-slate-100 p-6 lg:grid-cols-2"><div><h3 className="text-sm font-black text-slate-900">Authorization</h3><p className="mt-2 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{x.authorizationReason}</p></div><div><h3 className="text-sm font-black text-slate-900">Evidence</h3><div className="mt-2 space-y-2 text-sm">{x.officialProfileUrl&&<a href={x.officialProfileUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 font-semibold text-blue-600"><ExternalLink className="h-4 w-4"/>Official profile</a>}{x.evidenceUrl&&<a href={x.evidenceUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 font-semibold text-blue-600"><ExternalLink className="h-4 w-4"/>Evidence link</a>}{x.evidenceDescription&&<p className="rounded-xl bg-slate-50 p-3 text-slate-600">{x.evidenceDescription}</p>}{!x.officialProfileUrl&&!x.evidenceUrl&&!x.evidenceDescription&&<p className="text-slate-500">No evidence links supplied.</p>}</div></div></div>
   {!["REJECTED","REGISTERED"].includes(x.status)&&<div className="border-t border-slate-200 bg-slate-50 p-6"><label className="block text-sm font-bold text-slate-700">Review note</label><textarea value={notes[x.id]||""} onChange={e=>setNotes(p=>({...p,[x.id]:e.target.value}))} rows={3} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-blue-500" placeholder="Record what you verified or what is still required."/><div className="mt-4 flex flex-wrap gap-3"><button disabled={!!busy} onClick={()=>review(x.id,"APPROVE")} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>Approve & send code</button><button disabled={!!busy} onClick={()=>review(x.id,"MORE_INFORMATION_REQUIRED")} className="inline-flex items-center gap-2 rounded-xl border border-amber-300 bg-white px-4 py-3 text-sm font-bold text-amber-700 disabled:opacity-50"><HelpCircle className="h-4 w-4"/>Request more information</button><button disabled={!!busy} onClick={()=>review(x.id,"REJECT")} className="inline-flex items-center gap-2 rounded-xl border border-red-300 bg-white px-4 py-3 text-sm font-bold text-red-700 disabled:opacity-50"><XCircle className="h-4 w-4"/>Reject</button></div></div>}
  </article>)}</div>}
 </main>
}
function Info({title,rows}:{title:string;rows:string[][]}){return <div><h3 className="text-sm font-black text-slate-900">{title}</h3><dl className="mt-3 divide-y divide-slate-100 rounded-2xl border border-slate-200">{rows.map(([a,b])=><div key={a} className="grid grid-cols-[150px_1fr] gap-3 p-3 text-sm"><dt className="font-semibold text-slate-500">{a}</dt><dd className="break-words text-slate-800">{b}</dd></div>)}</dl></div>}
