"use client";

import { useEffect,useMemo,useState } from "react";
import { Send, ShieldCheck } from "lucide-react";

type Item={id:string;title:string;type:string};

export function RequestVerification(){
  const [items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{fetch("/api/profile",{cache:"no-store"}).then(r=>r.json()).then(data=>{const d=data.user?.profile?.fullData||{};const list:Item[]=[];(d.experiences||[]).forEach((x:any)=>list.push({id:String(x.id),title:x.role+" — "+x.company,type:"EXPERIENCE"}));(d.educations||[]).forEach((x:any)=>list.push({id:String(x.id),title:x.degree+" — "+x.institution,type:"EDUCATION"}));(d.projects||[]).forEach((x:any)=>list.push({id:String(x.id),title:x.title,type:"PROJECT"}));(d.achievements||[]).forEach((x:any)=>list.push({id:String(x.id),title:x.title,type:"ACHIEVEMENT"}));setItems(list);if(list[0])setSelected(list[0].id)}).catch(()=>{})},[]);
  const item=useMemo(()=>items.find(x=>x.id===selected),[items,selected]);
  const submit=async()=>{if(!item||!name.trim()||!email.trim())return;setSaving(true);try{const r=await fetch("/api/verification/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:item.type,itemId:item.id,title:item.title,verifierName:name,verifierEmail:email})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to create request");const url=location.origin+j.verificationUrl;await navigator.clipboard.writeText(url);setMessage("Verification link created and copied. Send it to the verifier.");}catch(e:any){setMessage(e.message)}finally{setSaving(false)}};
  return <section className="rounded-3xl border border-blue-100 bg-blue-50/40 p-6 sm:p-8 shadow-sm space-y-5"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-blue-600"/><h2 className="text-base font-black text-slate-900">Request Verification</h2></div><p className="mt-1 text-xs text-slate-600">Ask an employer, university, professor or project supervisor to verify a career record.</p></div>{items.length===0?<p className="rounded-2xl bg-white border border-blue-100 p-4 text-xs text-slate-500">Add an experience, education, project or achievement first.</p>:<><select value={selected} onChange={e=>setSelected(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm">{items.map(x=><option key={x.id} value={x.id}>{x.type}: {x.title}</option>)}</select><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Verifier name" className="rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Verifier email" className="rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm"/></div><button onClick={submit} disabled={saving||!name.trim()||!email.trim()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-blue-700 disabled:opacity-50"><Send className="h-4 w-4"/>{saving?"Creating...":"Create verification request"}</button>{message&&<p className="text-xs font-semibold text-blue-700">{message}</p>}</>}</section>;
}
